export const projects = [
  {
    id: 0,
    desc: "lorem ipsum 1",
    title: "Website Medisana",
    img: "https://raw.githubusercontent.com/bimbaquingoch/proyecto7mo/master/public/assets/medisana.png",
    created: "date",
    tech: "nodeJS, HBS, html, bootstrap, css ",
    url: "https://medisana.herokuapp.com/",
  },
  {
    id: 1,
    desc: "lorem ipsum 2",
    title: "piano auth system",
    img: "https://raw.githubusercontent.com/bimbaquingoch/authPiano/master/media/piano.png",
    created: "date",
    tech: "nodeJs , HBS , mongoDB , html , css , bootstrap",
    url: "https://auth-piano.herokuapp.com/",
  },
  {
    id: 2,
    desc: "lorem ipsum 3",
    title: "simple ecommerce",
    img: "https://raw.githubusercontent.com/bimbaquingoch/ecommerce-React/master/media/ecommerce.png",
    created: "date",
    tech: "react , firebase , stripe , material ui , fakestoreApi",
    url: "https://bimbaquingoch.github.io/ecommerce-React/",
  },
  {
    id: 3,
    desc: "Simple landing page usign html and css",
    title: "Bata bit ",
    img: "https://raw.githubusercontent.com/bimbaquingoch/mobileFirst/master/assets/imgs/bitcoinbaby.png",
    created: "date",
    tech: "html , css",
    url: "https://bimbaquingoch.github.io/mobileFirst/",
  },
  {
    id: 4,
    desc: "lorem ipsum 4",
    title: "my neovim config",
    img: "https://raw.githubusercontent.com/bimbaquingoch/newNvcode/master/utils/images/nvcode.png",
    created: "date",
    tech: "vimL , lua ",
    url: "https://github.com/bimbaquingoch/newNvcode",
  },
];
