export const projects = [
  {
    id: 0,
    desc: "Medical website using nodejs, hbs and deployed on heroku",
    title: "Website Medisana",
    img: "https://raw.githubusercontent.com/bimbaquingoch/proyecto7mo/master/public/assets/medisana.png",
    created: "17 - 06 - 2020",
    tech: "nodeJS, HBS, html, bootstrap, css, heroku ",
    url: "https://medisana.herokuapp.com/",
  },
  {
    id: 1,
    desc: "Auth system using nodejs, hbs and deployed on heroku",
    title: "piano auth system",
    img: "https://raw.githubusercontent.com/bimbaquingoch/authPiano/master/media/piano.png",
    created: "12 - 05 - 2021",
    tech: "nodeJs , HBS , mongoDB , html , css , bootstrap, heroku",
    url: "https://auth-piano.herokuapp.com/",
  },
  {
    id: 2,
    desc: "Simple e-commerce using react, material ui and deployed on github pages",
    title: "simple ecommerce",
    img: "https://raw.githubusercontent.com/bimbaquingoch/ecommerce-React/master/media/ecommerce.png",
    created: "17 - 06 - 2021",
    tech: "react , firebase , stripe , material ui , fakestoreApi",
    url: "https://bimbaquingoch.github.io/ecommerce-React/",
  },
  {
    id: 3,
    desc: "Simple landing page usign html and css",
    title: "Bata bit ",
    img: "https://raw.githubusercontent.com/bimbaquingoch/mobileFirst/master/batabit.png",
    created: "17 - 03 - 2021",
    tech: "html , css",
    url: "https://bimbaquingoch.github.io/mobileFirst/",
  },
  {
    id: 4,
    desc: "My personal neovim config forked from Lunarvim",
    title: "my neovim config",
    img: "https://raw.githubusercontent.com/bimbaquingoch/newNvcode/master/utils/images/nvcode.png",
    created: "11 - 11 - 2020",
    tech: "vimL , lua",
    url: "https://github.com/bimbaquingoch/newNvcode",
  },
];

export const skils = [
  "html",
  "css",
  "Javascript",
  "typescript",
  "styled components",
  "python",
  "react",
  "angular",
  "bootstrap",
  "bulma css",
  "material UI",
  "Git",
  "Github",
  "Terminal",
  "Heroku",
  "postman",
  "Insomnia",
  "Neovim",
  "NodeJS",
  "MongoDB",
  "figma",
  "flask",
];
