import { BgCircles, Circle } from "./StyledComponents";

export const Circles = () => (
   <BgCircles>
      <Circle
         top='10'
         left='5'
         color='3b5999'
         size='25'
         animation='zoomInOut'
         time='5'
      />
      <Circle
         top='20'
         left='35'
         color='e4405f'
         size='20'
         animation='bounceTop'
         time='5'
      />
      <Circle
         top='50'
         left='55'
         color='57c181'
         size='10'
         animation='bounceTop'
         time='5'
      />
      <Circle
         top='65'
         left='50'
         color='55acee'
         size='8'
         animation='zoomInOut'
         time='5'
      />
      <Circle
         top='80'
         left='25'
         color='ff062b'
         size='8'
         animation='zoomInOut'
         time='5'
      />
      <Circle
         top='25'
         left='75'
         color='051f2b'
         size='12'
         animation='zoomInOut'
         time='8'
      />
      <Circle
         top='80'
         left='85'
         color='e4405f'
         size='30'
         animation='bounceTop'
         time='5'
      />
   </BgCircles>
);
